#!/usr/bin/env ruby

require 'rubygems'
require 'daemons'

SINATRA_ROOT = File.expand_path(File.dirname(__FILE__) + '/..')

Daemons.run "#{SINATRA_ROOT}/mortgage.rb",
  :mode       => :load,
  :dir        => SINATRA_ROOT,
  :dir_mode   => :normal,
  :log_output => true,
  :app_name   => 'mort'
